config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root to: "posts#index"
	resources :posts, only: [:index, :show, :new, :create, :destroy] do
		resources :likes, only: :create
	end

	resources :likes, only: :destroy
	resources :users, only: :show

<<<<<<< Updated upstream
=======
<<<<<<< Updated upstream
=======
>>>>>>> Stashed changes
	namespace :api do
		namespace :v1 do
			resources :posts, only: :none do
				resources :likes, only: [:create]
			end
			namespace :gurunavi do
				get "/search", :action  => "search"
				get "/", :action => "new"
			end
		end
	end

<<<<<<< Updated upstream
	#to do likesのresourcesで書く
	delete "api/v1/posts/:post_id/likes" => "api/v1/likes#destroy"
=======
	resources :users do
		resources :relationships, only: [:create, :destroy]
		get :follows, on: :member 
		get :followers, on: :member 
	end
	#to do likesのresourcesで書く
	delete "api/v1/posts/:post_id/likes" => "api/v1/likes#destroy"
>>>>>>> Stashed changes
>>>>>>> Stashed changes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user 
    has_many :likes
    validates :content, {presence: true}
    mount_uploader :image, ImagesUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
				 :recoverable, :rememberable, :validatable 
				#  :confirmable
  has_many :posts
	has_many :likes
	has_many :relationships
	has_many :followings, through: :relationships, source: :follow
	has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
	has_many :followers, through: :reverse_of_relationships, source: :user

	def follow(other_user)
		unless self == other_user
			self.relationships.find_or_create_by(follow_id: other_user.id)
		end
	end

	def unfollow(other_user)
		relationship = self.relationships.find_by(follow_id: other_user.id)
		relationship.destroy if relationship
	end
	
	def followings?(other_user)
		self.followings.include?(other_user)
	end
end

app/controllers/api/v1/gurunavi_controller.rb
class Api::V1::GurunaviController < ApplicationController
	require 'json'
	require 'net/http'
  require 'uri'


	def new
	end

	def search
		word = params[:search]

		data={
      "keyid": "3bcaa2b3599317db755b92eeb01cd7ef",
      "freeword": word
		}
		query = data.to_query
		uri = "https://api.gnavi.co.jp/RestSearchAPI/v3/?" + query
		url = URI.parse uri
		json = Net::HTTP.get(url)
		results = JSON.parse(json)
		@shops = results['rest']
		
	# 	url = URI.encode url
	# 	p url
	# 	json = open(url)
	# 	puts "aaaaaaaaaaaaaaaaaaaaaa"
	# 	hash = Hash.from_xml json
	# 	puts '=============='
	# 	shops = []
	# 	puts shops

  #   if hash.has_key?("response")
  #     hash["response"]["rest"].each do |shop|
  #       shops.push({
  #         name: shop["name"],
  #         url: shop["url"],
  #         opentime: shop["opentime"],
  #         holiday: shop["holiday"],
  #         image1: shop["image_url"]["shop_image1"],
  #         image2: shop["image_url"]["shop_image2"]
  #       })
  #     end
  #   elsif hash.has_key?("gnavi")
  #     if hash["gnavi"].has_key?("error")
  #         if hash["gnavi"]["error"]["code"] == "600"
  #           @error = "該当する店舗の情報が存在しません"
  #         end
  #     end
  #   else
  #     @error = "エラーが発生しました"
  #   end

  #   rescue
  #     @error = "エラーが発生しました"
  #   end
	 end
	end

app/controllers/api/v1/likes_controller.rb
class Api::V1::LikesController < ApplicationController
	def create
		like = Like.new(user_id: current_user.id, post_id: params[:post_id])
		p "!!!!!!!!!!!"
		like.save
		render :json => { success: true }
	end
	
	def destroy
		like = Like.find_by(user_id: current_user.id, post_id: params[:post_id])
		like.destroy
		p "!!!!!!!!"
		render :json => { success: true }
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	
	def authenticate
		redirect_to new_user_registration_path unless user_signed_in?
	end 

	def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profile]) # 新規登録時(sign_up時)にnameというキーのパラメーターを追加で許可する
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :authenticate
    def create
			like = Like.new(user_id: current_user.id, post_id: params[:post_id])
			like.save
			redirect_to(post_path(id: params[:post_id]))
		end
		
		def destroy
			like = Like.find(params[:id])
			post = like.post
			like.destroy
			redirect_to(post_path(post))
		end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate, only: [:new, :create]

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(
            content: params[:content],
            user: current_user,
            image: params[:image]
				)
				if  @post.save
						redirect_to(post_path(@post))
				else
            render(:new)
        end
    end

		def index
				@posts = Post.all.order(created_at: :desc)
				binding.pry
    end

    def show
				@post = Post.find(params[:id])
				# @like = Like.find_by(user: current_user, post: @post)
				@like = @post.likes.find_by(user: current_user)
		end 
		
		def destroy
			@post = Post.find(params[:id]).destroy
			redirect_to user_path(current_user)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meshinsta</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

		<link rel="stylesheet" type="text/css" href="/css/reset.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>-------</h1>

app/views/partials/_footer.html.erb
<footer id="footer">
</footer>

app/views/partials/_header.html.erb
<header id="header">
	<a href="/" class="logo"><img src="/img/onigirilogo.svg"></a>
	<% if user_signed_in? %>
		<%= link_to "投稿", new_post_path, {class: "post-button"} %>
		<%= link_to "ログアウト", destroy_user_session_path, { method: "delete", class: "sign-out"} %>
	<% else %>
		<%= link_to "ログイン", new_user_session_path, {class: "sign-in"} %>
		<%= link_to "新規登録", new_user_registration_path, {class: "sign-up"} %>
	<% end %>
</header>

app/views/posts/index.html.erb
<%= render partial: "partials/header" %>
<main id="posts-index">
  <%=link_to '店舗検索↗', api_v1_gurunavi_path, class: "search_shops"%>
	<ul>
		<% @posts.each do |post| %>
				<li>
					<%=link_to post_path(post) do %>
						<div class="img" style="background-image: url(<%= post.image.to_s %>);"></div>
					<% end %>
				</li>
		<% end %>
	</ul>
</main>
<%= render partial: "partials/footer" %>

app/views/posts/new.html.erb
<%= render partial: "partials/header" %>

<% @post.errors.full_messages.each do |message| %>
    <%= message %>
<% end %>

<main id="post-new">
	<div class="inner">
		<div class="inner-inner">
			<%= form_tag(posts_path, multipart: true) do %>
				<div>
					<textarea name="content" class="text-new"></textarea>
				</div>
				<div class="footer">
					<div>
						<%= file_field_tag :image, class: "picture" %>
					</div>
					<div class="submit">
						<input type="submit" value="投稿" class="submit_btn">
					</div>
				</div>
			<% end %>
		</div>
	</div>
</main>

<%= render partial: "partials/footer" %>

app/views/posts/show.html.erb
<%= render partial: "partials/header" %>
<main id="posts-show">
	<div class="inner">
		<div class="img" style="background-image: url(<%= @post.image.to_s %>);"></div>
		<div class="details">
		  <%=link_to user_path(@post.user_id) do %>
		　  <div class="user_name">Contributor★<%=@post.user.name%></div>
		  <% end %>
			<div class="content">
				<%= @post.content %>
			</div>

			<footer>
<<<<<<< Updated upstream
				<% if @like %>
					<a data-post-id=<%= @post.id %> class="dislike" href="">食べたい</a> 
				<% else %>
<<<<<<< Updated upstream
					<a data-post-id=<%= @post.id %> class="like" href="">食べたい</a> 
=======
					<a class="like" href="">食べたい</a> 
=======
			　<% if @post.user != current_user %>
					<% if @like %>
						<a data-post-id=<%= @post.id %> class="dislike" href="">食べたい</a> 
					<% else %>
						<a data-post-id=<%= @post.id %> class="like" href="">食べたい</a> 
					<% end %>
				<% end %>

				<% if @post.user == current_user %>
				  <%=link_to "削除", post_path(@post), method: :delete %>
>>>>>>> Stashed changes
>>>>>>> Stashed changes
				<% end %>
			</footer>
		</div>
	</div>
</main>
<%= render partial: "partials/footer" %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
	<%= link_to "ログイン", new_session_path(resource_name), class: "login-button" %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
	<%= link_to "新規登録", new_registration_path(resource_name), class: "registaration" %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
	<%= link_to "パスワードをお忘れですか？", new_password_path(resource_name), class: "forget-password" %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
	<%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
	<%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
	<%- resource_class.omniauth_providers.each do |provider| %>
		<%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
	<% end %>
<% end %>

app/views/users/show.html.erb
<%= render partial: "partials/header" %>
<main id="users-show">
	  <div class="user_name"><%=@user.name%>のページ</div>
  	<ul>
	  	<% @user.posts.each do |post| %>
	    <li>
			  <div class="img" style="background-image: url(<%= post.image.to_s %>)"></div>
			</li>
	  	<% end %>
	  </ul>
</main>
<%= render partial: "partials/footer" %>